spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 110110
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
  jpa:
    show-sql: true